# Generated by Django 5.1.2 on 2024-12-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='materials_table',
            field=models.ManyToManyField(related_name='tables', to='my_test.materials'),
        ),
    ]
