# Generated by Django 5.1.3 on 2024-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='authors',
            field=models.ManyToManyField(related_name='recipes_authors', to='my_app.author'),
        ),
    ]
