# Generated by Django 5.1.3 on 2024-11-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='modified_date',
        ),
    ]
