# Generated by Django 5.1.3 on 2024-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_menu_name_alter_menu_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Ссылка'),
        ),
    ]
