# Generated by Django 5.1.3 on 2024-11-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_category_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='modified_date',
        ),
    ]
