# Generated by Django 5.1.3 on 2024-11-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_category_description_alter_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='authors',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='my_app.author'),
        ),
    ]
