# Generated by Django 5.1.3 on 2024-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_item_modified_date_work_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_measurement',
            field=models.CharField(default='кг', max_length=20),
        ),
    ]
