# Generated by Django 5.1.3 on 2024-11-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_item_unit_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='works',
        ),
        migrations.AddField(
            model_name='recipe',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specification_recipes', to='my_app.specification'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_steps',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_steps',
            field=models.ManyToManyField(related_name='works_recipes', to='my_app.work'),
        ),
    ]
