# Generated by Django 5.1.3 on 2024-11-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_recipe_materials_remove_recipe_works_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='operation',
        ),
    ]
