# Generated by Django 5.1.3 on 2024-11-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_remove_specification_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='items',
        ),
    ]
