# Generated by Django 5.1.3 on 2024-11-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_remove_recipe_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_steps',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_steps',
            field=models.CharField(default='', max_length=200),
        ),
    ]
