# Generated by Django 5.1.3 on 2024-11-21 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_remove_recipe_cooking_steps_recipe_cooking_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='items',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification_recipes', to='my_app.specification'),
        ),
    ]
