# Generated by Django 5.1.3 on 2024-11-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_recipe_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='items',
        ),
    ]
