# Generated by Django 5.1.3 on 2024-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_specification_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
