# Generated by Django 5.1.3 on 2024-11-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_alter_specification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
    ]
