# Generated by Django 5.1.3 on 2024-11-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_specification_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='name',
            new_name='title',
        ),
    ]
