# Generated by Django 5.1.3 on 2024-11-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_rename_name_specification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='my_app.item'),
        ),
    ]
