# Generated by Django 5.1.3 on 2024-11-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_alter_specification_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='title',
            new_name='name',
        ),
    ]
