# Generated by Django 5.1.3 on 2024-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_rename_title_specification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bol_val',
            field=models.BooleanField(default=True),
        ),
    ]
