# Generated by Django 5.1.3 on 2024-11-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_recipe_bol_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='bol_val',
        ),
    ]
