# Generated by Django 5.1.3 on 2024-11-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_remove_recipe_bol_val'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specification',
            new_name='SpecificationRecipe',
        ),
    ]
