# Generated by Django 5.1.3 on 2024-11-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_rename_specification_specificationrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecificationRecipe',
        ),
    ]
