# Generated by Django 5.1.3 on 2024-11-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0039_alter_recipe_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='items',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specification_recipes', to='my_app.specification'),
        ),
    ]
