# Generated by Django 5.1.3 on 2024-11-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0040_alter_recipe_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='my_app.item'),
        ),
    ]
