# Generated by Django 5.1.3 on 2024-11-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_specification_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='items',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img'),
        ),
    ]
