# Generated by Django 5.1.3 on 2024-11-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_remove_recipe_items_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='modified_date',
        ),
    ]
